---
benchmark:
  php:
    enabled: true
  disk:
    enabled: true
    cycles: 10
  cpu:
    enabled: true
    math:
      count: 99999
    strings:
      count: 99999
    loops:
      count: 99999
    ifElse:
      count: 99999
  mysql:
    enabled: true
    count: 10000
    hostname: mysql-s
    port: 3306
    username: s507732rw
    password: *redacted*
    database: s507732_microban